import type { Metadata } from "next";
import "../../globals.css";
import { Header } from "@/components/layout/Header.component";
import { Footer } from "@/components/layout/Footer.component";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="de"
            className={`h-full antialiased`}
        >
            <body className="min-h-full flex flex-col bg-bg text-text">
                <Header />
                <main>
                    {children}
                </main>
            </body>
        </html>
    );
}
