services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - /data/next-dlrg-swim/mongo:/data/db
  next:
    build: ./packages/next
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      DEFAULT_USER_EMAIL: ${DEFAULT_USER_EMAIL}
      DEFAULT_USER_PASSWORD: ${DEFAULT_USER_PASSWORD}
      SALT: ${SALT}
      MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
  nginx: 
    build: ./.docker/nginx
    restart: unless-stopped
    depends_on:
      - next
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PATH_2_FULLCHAIN}:/certs/fullchain.pem:ro
      - ${PATH_2_PRIVATEKEY}:/certs/privkey.pem:ro