services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - /data/next-dlrg-swim/mongo:/data/db
  next:
    build: ./packages/next
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      DEFAULT_USER_EMAIL: admin@admin.com
      DEFAULT_USER_PASSWORD: admin123
      SALT: asdlfkjasöldfjöaslfLKJasdf
      MONGO_CONNECTION_STRING: mongodb://mongo:mongo@mongo:27017
  nginx: 
    build: ./.docker/nginx
    restart: unless-stopped
    depends_on:
      - next
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/next-dlrg-swim/certs:/certs