import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="flex min-h-screen items-center justify-center h-full bg-dlrg-red text-black">
        <div className="bg-white rounded-md">{children}</div>
      </body>
    </html>
  );
}
