import { Spinner } from "@/src/app/(admin)/admin/Spinner";
import type { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function SuspenseLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <Suspense fallback={<Spinner />}>
        {children}
    </Suspense>;
}
