export * from './login'
export * from './colors'

export * from './dateToGermanyDate.function'
export * from './getAge.function'
export * from './getGenderString.function'
export * from './preventPreRendering.function'
export * from './flat.function'
export * from './getYouthMedal'
export * from './sleep.function'