import type { Metadata } from "next";
import "../../globals.css";
import { Sidebar } from "./Sidebar";

export const metadata: Metadata = {
  title: "DLRG Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="h-full flex flex-col bg-dlrg-red text-black">
        <div className="flex md:flex-row flex-col relative">
          {/* The sidebar wrapper must have h-screen and sticky */}
          <aside className="sticky top-0 md:h-screen shrink-0">
            <Sidebar />
          </aside>

          <main className="flex-1 min-w-0 px-4 md:px-16 lg:px-32 bg-white grow min-h-screen">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
