import type { Metadata } from "next";
import "../../globals.css";

export const metadata: Metadata = {
  title: "DLRG Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="container mx-auto px-4 md:px-8 lg:px-16">
          {children}
        </div>
      </body>
    </html>
  );
}
