import type { Metadata } from "next";
import "../../globals.css";
import { Header } from "@/components/layout/Header.component";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="de"
            className={`h-full antialiased`}
        >
            <body className="min-h-full flex flex-col bg-bg text-text">
                <div className="flex h-screen items-center justify-center bg-gray-100">
                    <div className="p-8 bg-white rounded-lg shadow-md">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
